language: node_js
node_js:
- node

branches:
  only:
  - main
  - /^snyk-upgrade-[a-z0-9]{32}$/

after_success:
- yarn lint
- yarn test --coverage --coverageReporters=text-lcov | ./node_modules/.bin/coveralls
