sudo: false

language: node_js
node_js:
- node

branches:
  only:
  - master
  - /^greenkeeper/.*$/

cache:
  directories:
  - node_modules

before_install:
- yarn upgrade

install:
- yarn

script:
- yarn run test
- yarn run test --coverage --coverageReporters=text-lcov | ./node_modules/.bin/coveralls
