language: node_js
node_js:
- node

branches:
  only:
  - master
  - /^greenkeeper/.*$/

after_success:
- yarn lint
- yarn test --coverage --coverageReporters=text-lcov | ./node_modules/.bin/coveralls
