name: elements-check

on:
  push:
    branches:
      - main
      - /^snyk-upgrade-[a-z0-9]{32}$/
  pull_request:
    branches:
      - main
      - /^snyk-upgrade-[a-z0-9]{32}$/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installs dependencies
        run: yarn
      - name: Lint JavaScript
        run: yarn lint:js
      - name: Lint CSS
        run: yarn lint:css
      - name: Check flow coverage
        run: yarn flow:coverage
      - name: Check test coverage
        run: yarn test --coverage --coverageReporters=text-lcov | ./node_modules/.bin/coveralls
